allowBuilds:
  '@discordjs/opus': true
  '@nestjs/core': true
  '@swc/core': true
  esbuild: true
engineStrict: true
minimumReleaseAgeExclude:
  - zod@4.6.1
onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@nestjs/core'
  - unrs-resolver
